# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8c56f8ab80b856ad7a7abfd18a2eb2534aeef6b3af64774a5e7749208af4d80d7f1225d6cd49a70882154ff05b71b0a06d7c7b1eb0de7e69fbf522eb4858adf

test:
  secret_key_base: 2d93576236eca175e7cd17670520cf52a29860c78367a2b19dcfd8dbd0f286b96d86ef50e7a70b6862d432d895438c20a98fa3d480b10e7b8116c080fe1e9796

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
